#! /bin/bash
if [[ "$1" == "start" ]]; then
	docker run --init -d \
	--name homeassistant \
	--restart=unless-stopped \
	-v /home/pi/homeassistant:/config \
	-v /etc/localtime:/etc/localtime:ro \
	--network=host \
	homeassistant/raspberrypi3-homeassistant:stable
elif [[ "$1" == "update" ]]; then
	docker pull homeassistant/raspberrypi3-homeassistant:stable
	docker stop homeassistant
	docker rm homeassistant
	anton-app-homeassistant start
else
	echo "No argument - either 'start' or 'update' accepted."
fi