#!/bin/bash
echo "Check the following is in your /boot/cmdline.txt, or the Docker install might fail."
echo "cgroup_enable=memory cgroup_memory=1"

read -p "Did you check, and wish to continue? [y/N] " -n 1 -r
echo 
if [[ $REPLY =~ ^[Yy]$ ]]
then
        dockerscript=/home/pi/scripts/docker.sh
        rm dockerscript
        curl -fsSL https://get.docker.com -o dockerscript
        sh dockerscript
        sudo usermod -aG docker pi
        rm dockerscript

        # Ideal method, but doesn't currently work because of https://github.com/docker/compose/issues/6831.
        #sudo curl -L --fail https://github.com/docker/compose/releases/download/1.28.2/run.sh -o /usr/local/bin/docker-compose
        #sudo chmod +x /usr/local/bin/docker-compose
        sudo apt-get install python3 python3-pip -y
        python3 -m pip install -IU docker-compose
else
        echo "Aborted.";
fi
